baseURL = "https://simon-lu.github.io"
languageCode = "zh-CN"
title = "2+2=5"
theme = "mogege"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
hasCJKLanguage = true

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Pastime"
    url = "/pastime/"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[params]
    since = 2020
    author = "Simon Lu"                           # Author's name
    avatar = "/images/avatar.png"           # Author's avatar
    subtitle = "Welcome to The Machine"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "simon-lu"
    Email = "wq.lu@outlook.com"
    # Instagram = "xxoo"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    # Facebook = "xxoo"
    # Telegram = "xxoo"
    # Dribbble = "xxoo"
    # Medium = "xxoo"

[markup.goldmark.renderer]
    unsafe = true


# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
    enable = true
    appId = 'VAKj7pbBgLO64CwuFHW5qp1b-gzGzoHsz'
    appKey = 'RI6nmmeq9hVDSsfVESdshbRg'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'retro' 
    placeholder = '说点什么吧...'
    visitor = true

[params.aplayer]
    enable = true
    server = "netease"
    type = "playlist"
    id = "36180038"
    fixed = true
    preload = "auto"
    order = "random"

[params.custom]
    css = ["css/aplayer.css"]
    # js = ["js/_custom.js"]